name: link-prediction
channels:
  - pytorch
  - conda-forge
dependencies:
  - cudatoolkit=10.2.89
  - graph-tool=2.37
  - matplotlib=3.3.4
  - mkl=2024.0.0
  - optuna=2.10.0
  - pip=21.0.1
  - python=3.8.8
  - pytorch=1.8.0
  - rdkit=2020.09.5
  - seaborn=0.11.1
  - scikit-learn=0.24.1
  - pip:
    - --find-links https://data.pyg.org/whl/torch-1.8.0+cu102.html
    - numpy==1.20.1
    - pandas==1.1.5
    - torch-geometric==1.7.0
    - torch-scatter==2.0.6
    - torch-sparse==0.6.9

